import artistKeywords from "./artist-keywords";

function resolveBaseUrl(): string {
  const env = process.env.NEXT_PUBLIC_BASE_URL;
  if (env && !env.includes("localhost") && !env.includes("127.0.0.1")) return env;
  return "https://blueeyeentertainment.in";
}

const baseUrl = resolveBaseUrl();
const brandName = process.env.NEXT_PUBLIC_BRAND_NAME;

export interface SiteConfig {
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  url: string;
  ogImage: string;
  author: string;
  mainKeywords: string[];
  links: {
    twitter?: string;
    instagram?: string;
    facebook?: string;
    youtube?: string;
  };
  twitterHandle?: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
  address2?: string;
}

export const siteConfig: SiteConfig = {
  name: brandName || "Blue Eye Entertainment",
  shortName: process.env.NEXT_PUBLIC_BRAND_SHORT_NAME || brandName || "Blue Eye Entertainment",
  description: `Book India's Top Artists - Singers, DJs, Comedians & more for your events via ${brandName || "Blue Eye Entertainment"}. Premium entertainment at your fingertips.`,
  longDescription: `${brandName || "Blue Eye Entertainment"} is India's leading platform for booking premium entertainment. From Bollywood singers and high-energy DJs to corporate comedians and live bands, we provide high-quality artist management services for weddings, corporate events, and private parties.`,
  url: baseUrl,
  ogImage: `${baseUrl}/icon.png`,
  author: `${brandName || "Blue Eye Entertainment"} Team`,
  mainKeywords: [
    "blueeyeentertainment",
    "blue eye entertainment",
    "blue eyeentertainment",
    "Blue Eye Entertainment",
    "BlueEyeEntertainment",
    "Blue Eye",
    "BlueEye",
    "artist booking",
    "artist booking website",
    "cheap artist booking",
    "affordable artist booking india",
    "book bollywood singers",
    "hire famous singers india",
    "wedding entertainment india",
    "hire djs for corporate events",
    "live music bands for hire",
    "premium event entertainment",
    "artist management agency",
    "book stand up comedians",
    "hire celebrity for wedding",
    "indian artist booking agency",
    "book musicians for events",
    "live concert organizers india",
    "book rappers in india",
    "hire live bands for sangeet",
    "corporate event entertainment ideas",
    "book famous singers",
    "hire emcee for event",
    "book anchors for corporate events",
    "talent management company india",
    "celebrity management agency india",
    "hire instrumentalists",
    "book sufi singers",
    "hire punjabi singers",
    "wedding dj booking",
    "event entertainment services",
    "live performance booking",
    "top artist management companies",
    "book performers for private parties",
    "entertainment booking agency",
    "book local artists india",
    "artist booking app",
    "hire models for events",
    "book magicians india",
    "best wedding bands india",
    "hire dancers for wedding",
    "hire influencers india",
    "celebrity appearance booking",
    "book ghazal singers",
    "hire folk singers india",
    "gaane waale",
    "singer chahiye",
    "party mein singer",
    "shadi mein gaane",
    "sangeet ke liye singer",
    "mehendi ke liye artist",
    "baraat mein dj",
    "dj chahiye",
    "band chahiye",
    "event ke liye anchor",
    "party mein dancer",
    "comedian chahiye",
    "celebrity chahiye event ke liye",
    "artist booking kaise karein",
    "singer hire kaise karein",
    "online artist booking india",
    "instant artist booking",
    "book artist online india",
    "best wedding singer india",
    "top wedding band india",
    "famous singer for wedding",
    "best dj for wedding",
    "no 1 artist booking company",
    "number 1 entertainment company india",
    "leading artist management agency",
    "most trusted artist booking",
    "verified artists india",
    "genuine artist booking platform",
    "reliable entertainment agency",
    "experienced artist manager",
    "professional event entertainers",
    "top rated performers india",
    "recommended wedding entertainers",
    "affordable wedding singer india",
    "budget friendly event artist",
    "cheapest artist booking india",
    "reasonable singer fees",
    "singer price list india",
    "artist booking cost",
    "entertainment budget calculator",
    "celebrity booking fees india",
    "singer ki fees kitni hai",
    "artist ka price kya hai",
    "kitne mein aate hain singers",
    "shaadi ke liye singer price",
    "urgent artist booking",
    "last minute singer hire",
    "instant confirm booking",
    "same day artist booking",
    "book now pay later",
    "celebrity for event today",
    "pan india artist booking",
    "all india entertainment service",
    "artist booking delhi ncr",
    "artist booking mumbai",
    "artist booking bangalore",
    "artist booking hyderabad",
    "artist booking ahmedabad",
    "artist booking chennai",
    "artist booking kolkata",
    "artist booking pune",
    "artist booking jaipur",
    "artist booking lucknow",
    "artist booking surat",
    "artist booking indore",
    "artist booking chandigarh",
    "artist booking bhopal",
    "artist booking nagpur",
    "artist booking patna",
    "artist booking ludhiana",
    "artist booking agra",
    "artist booking varanasi",
    "artist booking guwahati",
    "artist booking raipur",
    "artist booking ranchi",
    "artist booking bhubaneswar",
    "artist booking coimbatore",
    "artist booking kochi",
    "artist booking goa",
    "artist booking vadodara",
    "artist booking nashik",
    "artist booking vizag",
    "artist booking madurai",
    "artist booking aurangabad",
    "artist booking jodhpur",
    "artist booking udaipur",
    "artist booking kota",
    "artist booking dehradun",
    "artist booking shimla",
    "artist booking amritsar",
    "artist booking jammu",
    "artist booking srinagar",
    "artist booking kerala",
    "artist booking punjab",
    "artist booking gujarat",
    "artist booking rajasthan",
    "artist booking bihar",
    "artist booking up",
    "artist booking maharashtra",
    "artist booking tamil nadu",
    "artist booking karnataka",
    "artist booking west bengal",
    "artist booking madhya pradesh",
    "artist booking haryana",
    "artist booking uttarakhand",
    "shaadi ke gaane wale",
    "sangeet ke singer",
    "mehendi ke dancer",
    "reception ke liye band",
    "engagement party entertainer",
    "ring ceremony dj",
    "tilak ceremony singer",
    "haldi event artist",
    "puja ke liye bhajan singer",
    "griha pravesh ke liye artist",
    "birthday party entertainer",
    "anniversary celebration singer",
    "college fest artist booking",
    "corporate party entertainer",
    "new year party singer",
    "new year eve dj booking",
    "diwali party entertainer",
    "ganpati utsav singer",
    "navratri garba artist",
    "holi party dj booking",
    "destination wedding india",
    "luxury wedding singer",
    "royal wedding entertainer",
    "celebrity appearance india",
    "book film star for event",
    "bollywood celebrity for wedding",
    "tv star for corporate event",
    "famous personality for product launch",
    "sports celebrity for event",
    "social media influencer for party",
    "youtuber for college fest",
    "instagram influencer for event",
    "bollywood playback singer wedding",
    "punjabi singer for sangeet",
    "sufi singer for mehendi",
    "ghazal singer for reception",
    "folk singer for engagement",
    "bollywood dancer for sangeet",
    "bhangra dancer for wedding",
    "garba dancer for navratri",
    "classical dancer for event",
    "western dancer for party",
    "live band for reception",
    "orchestra for wedding",
    "dhol player for baraat",
    "dholi for wedding procession",
    "shehnai player for puja",
    "nagada for garba",
    "stand up comedian for corporate",
    "magician for kids party",
    "anchoring for event",
    "emcee for wedding",
    "trumpet player for reception",
    "saxophone player for party",
    "pianist for event",
    "guitarist for sangeet",
    "tabla player for classical event",
    "flute player for mehendi",
    "best singer in india for event",
    "top entertainers in india",
    "famous artists for booking",
    "popular performers for party",
    "trending artists for wedding",
    "new artist for event",
    "upcoming singer for party",
    "viral artists for wedding",
    "trending dj for college fest",
    "best live band in india",
    "top comedy shows for corporate",
    "most wanted performers india",
    "a list celebrity booking",
    "b list celebrity for event",
    "regional celebrity booking",
    "south indian celebrity for event",
    "north indian artist for wedding",
    "singer phone number",
    "artist contact number",
    "dj contact number india",
    "band phone number",
    "comedian mobile number",
    "direct artist booking",
    "without agency artist hire",
    "artist management services near me",
    "wedding planner recommended artists",
    "event management approved singers",
    "5 star hotel wedding entertainer",
    "resort event performer",
    "farmhouse party artist",
    "banquet hall entertainment",
    "convention center performer",
    "open air event singer",
    "beach wedding entertainer",
    "pool party dj",
    "rooftop event singer",
    "garden wedding performer",
    "artist booking platform",
    "entertainment portal india",
    "artist directory india",
    "performer listing website",
    "talent marketplace india",
    "entertainment aggregator",
    "one stop event solution",
    "artist booking app india",
    "book performer app",
    "entertainment booking software",
    "panel of artists india",
    "curated artist list",
    "vetted performers india",
    "screened artists for events",
    "quality checked performers",
    "100% verified artists",
    "secure booking platform",
    "safe payment artist booking",
    "money back guarantee artists",
    "satisfaction guaranteed performers",
    "24/7 artist booking support",
    "event helpline india",
    "artist booking customer care",
    "entertainment consultant india",
    "free artist consultation",
    "personal event manager",
    "dedicated artist coordinator",
    "hassle free artist booking",
    "easy performer hire",
    "simple booking process",
    "quick artist booking",
    "fast event entertainer hire",
    "instant performer confirmation",
    "real time artist availability",
    "check artist availability online",
    "compare singer prices",
    "compare artist fees",
    "best price guarantee artists",
    "lowest price performers",
    "exclusive artist deals",
    "special discount on booking",
    "festival offer artist booking",
    "seasonal discount performers",
    "group booking discount singers",
    "multiple artist hire discount",
    "corporate event package",
    "wedding entertainment package",
    "complete event solution",
    "end to end event entertainment",
    "full event artist management",
    "artist management company delhi",
    "entertainment agency mumbai",
    "talent management firm india",
    "celebrity management company",
    "event production company india",
    "live event management",
    "performance management company",
    "artist representation india",
    "talent acquisition for events",
    "booking agent for artists",
    "artist manager in india",
    "personal manager for singer",
    "event coordinator for wedding",
    "entertainment planner india",
    "experience gift entertainment",
    "surprise performance booking",
    "flash mob for wedding",
    "celebrity surprise at event",
    "live performance gift",
    "singer for proposal",
    "engagement surprise entertainer",
    "birthday surprise performer",
    "anniversary gift singer",
    "book singer as gift",
    "corporate gift entertainment",
    "client entertainment event",
    "employee engagement performer",
    "team building activity artists",
    "office party entertainer",
    "company annual function singer",
    "product launch entertainer",
    "brand activation performer",
    "roadshow artist",
    "mall event entertainer",
    "festival organizer performer",
    "religious event singer",
    "temple festival artist",
    "gurudwara event singer",
    "church event performer",
    "cultural program entertainer",
    "school annual day performer",
    "college cultural fest singer",
    "university event booking",
    "sports event entertainer",
    "community event performer",
    "society gathering entertainment",
    "residential colony event singer",
    "club membership event artist",
    "event ticket included performer",
    "paid performance booking",
    "charity event entertainer",
    "fundraiser event singer",
    "ngo event performer",
    "political rally entertainer",
    "government event booking",
    "private concert organizer",
    "house party singer",
    "intimate wedding performer",
    "small event entertainer",
    "grand wedding performer",
    "large scale event artist",
    "stadium concert organizer",
    "arena show booking",
    "auditorium event performer",
    "indoor event singer",
    "outdoor festival entertainer",
    "evening party performer",
    "day event singer",
    "morning ceremony artist",
    "night wedding entertainer",
    "late night party dj",
    "weekend event booking",
    "weekday party performer",
    "book artist for today",
    "book artist for tomorrow",
    "available artists this week",
    "artists for this weekend",
    "next month event booking",
    "advance booking singers",
    "pre book artist for event",
    "early bird discount booking",
    "last minute deal entertainer",
    "flash sale artist booking",
    "tie up with artist agency",
    "become artist partner",
    "artist registration platform",
    "join as performer",
    "register as artist",
    "artist login portal",
    "performer dashboard",
    "artist panel access",
    "manage artist profile",
    "update artist portfolio",
    "artist booking analytics",
    "performer earning reports",
    "artist payment tracking",
    "autopay for performers",
    "instant payout for artists",
    "weekly payment artists",
    "monthly settlement performers",
    "secure payment gateway artists",
    "escrow payment booking",
    "partial payment booking",
    "advance payment artist",
    "full payment at event",
    "post event payment",
    "easy emi artist booking",
    "pay in installments performers",
    "no cost emi entertainer",
    "zero interest booking",
    "credit card payment artists",
    "upi payment artist booking",
    "net banking performers",
    "cash on event payment",
    "paytm booking artists",
    "google pay entertainer",
    "phonepe performer payment",
    "online transfer artist fees",
    "invoice for artist booking",
    "gst bill for performer",
    "tax invoice entertainer",
    "receipt for artist payment",
    "contract for artist booking",
    "agreement for performer",
    "terms and conditions booking",
    "cancellation policy artists",
    "reschedule performer booking",
    "refund policy entertainer",
    "artist replacement guarantee",
    "backup performer provided",
    "alternative artist arrangement",
    "dual artist booking option",
    "package deal two performers",
    "combo offer singer and dancer",
    "singer with band package",
    "dj with dancer package",
    "anchor with comedian combo",
    "full night entertainer package",
    "half day event performer",
    "hourly artist booking",
    "per song singer booking",
    "per set musician booking",
    "customized artist package",
    "tailored event entertainment",
    "bespoke performer selection",
    "personalized artist recommendation",
    "choose your own artist",
    "select performer by category",
    "browse artists by genre",
    "filter artists by price",
    "search artists by location",
    "find artist by language",
    "explore performers by rating",
    "discover new artists india",
    "trending performers near you",
    "popular artists in your city",
    "best entertainers in india",
    "top rated singers nation wide",
    "highest paid performers india",
    "most booked artists india",
    "frequently booked performers",
    "most viewed artist profile",
    "artist of the month",
    "featured performers india",
    "editor choice artists",
    "premium artists collection",
    "platinum performers list",
    "gold artists category",
    "silver performers tier",
    "basic artist package",
    "standard performer plan",
    "premium event package",
    "luxury entertainer collection",
    "vip artist booking",
    "exclusive performer access",
    "celebrity vip treatment",
    "red carpet event manager",
    "star studded event planner",
    "entertainment at its best",
    "world class performers india",
    "international artist booking",
    "global performer for event",
    "foreign artist for wedding",
    "nri wedding entertainer",
    "destination wedding performer goa",
    "udaipur wedding artist",
    "jaipur wedding entertainer",
    "jodhpur royal wedding singer",
    "agra wedding performer",
    "kerala wedding entertainer",
    "goa beach wedding dj",
    "manali wedding singer",
    "rishikesh wedding performer",
    "shimla wedding entertainer",
    "ooty wedding singer",
    "munnar wedding performer",
    "andaman wedding entertainer",
    "lakshadweep wedding artist",
    "international wedding entertainer",
    "singer for mehendi function",
    "artist for haldi ceremony",
    "performer for tilak event",
    "entertainer for sangeet night",
    "dj for wedding reception",
    "band for engagement party",
    "dancer for ring ceremony",
    "anchor for marriage function",
    "comedian for sangeet",
    "celebrity host for wedding",
    "surprise act for wedding",
    "wedding entertainment ideas",
    "unique wedding performers",
    "trending wedding entertainment",
    "modern wedding entertainer",
    "traditional wedding performer",
    "fusion band for wedding",
    "contemporary singer for event",
    "classical singer for puja",
    "folk artist for cultural event",
    "rock band for college fest",
    "indie artist for party",
    "pop singer for event",
    "hip hop artist for show",
    "rap artist for college fest",
    "edm dj for club night",
    "house music dj for party",
    "techno dj for event",
    "bollywood dj for wedding",
    "remix dj for sangeet",
    "punjabi dj for baraat",
    "retro dj for reception",
    "romantic singer for engagement",
    "melody singer for mehendi",
    "devotional singer for puja",
    "qawwali singer for event",
    "bhajan singer for religious ceremony",
    "shabad singer for gurudwara event",
    "gospel singer for church event",
    "carnatic singer for classical event",
    "hindustani classical vocalist",
    "playback singer for wedding",
    "reality show winner for event",
    "voice of india singer booking",
    "indian idol winner for wedding",
    "big boss celebrity for event",
    "roadies personality for party",
    "youtuber artist for event",
    "tiktok star now artist",
    "instagram reel artist booking",
    "social media sensation performer",
    "enterteinment booking",
    "entertinment artist hire",
    "artest booking india",
    "celebrety management agency",
    "talent managment company",
    "event managment entertainer",
    "bookking artist online",
    "performar for wedding",
    "enterment for party",
    "anjali",
    "book artist on call",
    "whatsapp artist booking",
    "text for artist hire",
    "call for singer booking",
    "email for performer hire",
    "enquiry for artist available",
    "quote for booking artist",
    "price list of singers",
    "artist rate card india",
    "performer fee structure",
    "entertainment cost india",
    "booking charges artist",
    "service fee entertainer",
    "commission for artist booking",
    "platform fee performer",
    "registration fee artist",
    "membership entertainer portal",
    "subscription artist booking",
    "free listing for artists",
    "premium listing performers",
    "featured artist cost",
    "promoted performer fee",
    "sponsored artist listing",
    "advertise your talent",
    "promote your performance",
    "get discovered as artist",
    "boost your artist profile",
    "increase booking for performers",
    "grow your event business",
    ...artistKeywords
  ],
  links: {
    twitter: process.env.NEXT_PUBLIC_TWITTER_URL,
    instagram: process.env.NEXT_PUBLIC_INSTAGRAM_URL,
    facebook: process.env.NEXT_PUBLIC_FACEBOOK_URL,
    youtube: process.env.NEXT_PUBLIC_YOUTUBE_URL,
  },
  twitterHandle: process.env.NEXT_PUBLIC_TWITTER_HANDLE,
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL,
  contactPhone: process.env.NEXT_PUBLIC_CONTACT_PHONE,
  address: process.env.NEXT_PUBLIC_CONTACT_ADDRESS_1,
  address2: process.env.NEXT_PUBLIC_CONTACT_ADDRESS_2,
};




